# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analysis.proto',
  package='analysis',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\xe8\x01\n\x0f\x41nalysisRequest\x12\n\n\x02\x65\x31\x18\x01 \x01(\x08\x12\n\n\x02\x65\x32\x18\x02 \x01(\x08\x12\n\n\x02\x65\x33\x18\x03 \x01(\x08\x12\n\n\x02\x65\x34\x18\x04 \x01(\x08\x12\x15\n\rbuy_or_follow\x18\x05 \x01(\x08\x12\x0e\n\x06profit\x18\x06 \x01(\x02\x12\x10\n\x08turnover\x18\x07 \x01(\x02\x12\x10\n\x08increase\x18\x08 \x01(\x02\x12\x13\n\x0bwin_percent\x18\t \x01(\x02\x12\x14\n\x0close_percent\x18\n \x01(\x02\x12\x12\n\nlose_cache\x18\x0b \x01(\x02\x12\x0c\n\x04\x64\x61ys\x18\x0c \x01(\x05\x12\r\n\x05\x66orce\x18\r \x01(\x08\"\xd0\x03\n\rAnalysisReply\x12\n\n\x02\x65\x31\x18\x01 \x01(\x08\x12\n\n\x02\x65\x32\x18\x02 \x01(\x08\x12\n\n\x02\x65\x33\x18\x03 \x01(\x08\x12\n\n\x02\x65\x34\x18\x04 \x01(\x08\x12\x15\n\rbuy_or_follow\x18\x05 \x01(\x08\x12\x15\n\rall_numerator\x18\x06 \x01(\x05\x12\x17\n\x0f\x61ll_denominator\x18\x07 \x01(\x05\x12\x12\n\nall_result\x18\x08 \x01(\x02\x12\x18\n\x10profit_numerator\x18\t \x01(\x05\x12\x1a\n\x12profit_denominator\x18\n \x01(\x05\x12\x15\n\rprofit_result\x18\x0b \x01(\x02\x12\x1a\n\x12turnover_numerator\x18\x0c \x01(\x05\x12\x1c\n\x14turnover_denominator\x18\r \x01(\x05\x12\x17\n\x0fturnover_result\x18\x0e \x01(\x02\x12\x1a\n\x12increase_numerator\x18\x0f \x01(\x05\x12\x1c\n\x14increase_denominator\x18\x10 \x01(\x05\x12\x17\n\x0fincrease_result\x18\x11 \x01(\x02\x12\x13\n\x0bprofit_sign\x18\x12 \x01(\t\x12\x15\n\rturnover_sign\x18\x13 \x01(\t\x12\x15\n\rincrease_sign\x18\x14 \x01(\t2S\n\x08\x41nalysis\x12G\n\x0fRequireAnalysis\x12\x19.analysis.AnalysisRequest\x1a\x17.analysis.AnalysisReply\"\x00\x42)\n\x10io.grpc.analysisB\rAnalysisProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_ANALYSISREQUEST = _descriptor.Descriptor(
  name='AnalysisRequest',
  full_name='analysis.AnalysisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e1', full_name='analysis.AnalysisRequest.e1', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e2', full_name='analysis.AnalysisRequest.e2', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e3', full_name='analysis.AnalysisRequest.e3', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e4', full_name='analysis.AnalysisRequest.e4', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buy_or_follow', full_name='analysis.AnalysisRequest.buy_or_follow', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit', full_name='analysis.AnalysisRequest.profit', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover', full_name='analysis.AnalysisRequest.turnover', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase', full_name='analysis.AnalysisRequest.increase', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='win_percent', full_name='analysis.AnalysisRequest.win_percent', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lose_percent', full_name='analysis.AnalysisRequest.lose_percent', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lose_cache', full_name='analysis.AnalysisRequest.lose_cache', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='days', full_name='analysis.AnalysisRequest.days', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force', full_name='analysis.AnalysisRequest.force', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=261,
)


_ANALYSISREPLY = _descriptor.Descriptor(
  name='AnalysisReply',
  full_name='analysis.AnalysisReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e1', full_name='analysis.AnalysisReply.e1', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e2', full_name='analysis.AnalysisReply.e2', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e3', full_name='analysis.AnalysisReply.e3', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e4', full_name='analysis.AnalysisReply.e4', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buy_or_follow', full_name='analysis.AnalysisReply.buy_or_follow', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_numerator', full_name='analysis.AnalysisReply.all_numerator', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_denominator', full_name='analysis.AnalysisReply.all_denominator', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_result', full_name='analysis.AnalysisReply.all_result', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit_numerator', full_name='analysis.AnalysisReply.profit_numerator', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit_denominator', full_name='analysis.AnalysisReply.profit_denominator', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit_result', full_name='analysis.AnalysisReply.profit_result', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover_numerator', full_name='analysis.AnalysisReply.turnover_numerator', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover_denominator', full_name='analysis.AnalysisReply.turnover_denominator', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover_result', full_name='analysis.AnalysisReply.turnover_result', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase_numerator', full_name='analysis.AnalysisReply.increase_numerator', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase_denominator', full_name='analysis.AnalysisReply.increase_denominator', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase_result', full_name='analysis.AnalysisReply.increase_result', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit_sign', full_name='analysis.AnalysisReply.profit_sign', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover_sign', full_name='analysis.AnalysisReply.turnover_sign', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increase_sign', full_name='analysis.AnalysisReply.increase_sign', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=728,
)

DESCRIPTOR.message_types_by_name['AnalysisRequest'] = _ANALYSISREQUEST
DESCRIPTOR.message_types_by_name['AnalysisReply'] = _ANALYSISREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalysisRequest = _reflection.GeneratedProtocolMessageType('AnalysisRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANALYSISREQUEST,
  __module__ = 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.AnalysisRequest)
  ))
_sym_db.RegisterMessage(AnalysisRequest)

AnalysisReply = _reflection.GeneratedProtocolMessageType('AnalysisReply', (_message.Message,), dict(
  DESCRIPTOR = _ANALYSISREPLY,
  __module__ = 'analysis_pb2'
  # @@protoc_insertion_point(class_scope:analysis.AnalysisReply)
  ))
_sym_db.RegisterMessage(AnalysisReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020io.grpc.analysisB\rAnalysisProtoP\001\242\002\003HLW'))

_ANALYSIS = _descriptor.ServiceDescriptor(
  name='Analysis',
  full_name='analysis.Analysis',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=730,
  serialized_end=813,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequireAnalysis',
    full_name='analysis.Analysis.RequireAnalysis',
    index=0,
    containing_service=None,
    input_type=_ANALYSISREQUEST,
    output_type=_ANALYSISREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSIS)

DESCRIPTOR.services_by_name['Analysis'] = _ANALYSIS

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class AnalysisStub(object):
    """The analysis service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.RequireAnalysis = channel.unary_unary(
          '/analysis.Analysis/RequireAnalysis',
          request_serializer=AnalysisRequest.SerializeToString,
          response_deserializer=AnalysisReply.FromString,
          )


  class AnalysisServicer(object):
    """The analysis service definition.
    """

    def RequireAnalysis(self, request, context):
      """Sends an analysis request
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'RequireAnalysis': grpc.unary_unary_rpc_method_handler(
            servicer.RequireAnalysis,
            request_deserializer=AnalysisRequest.FromString,
            response_serializer=AnalysisReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'analysis.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAnalysisServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The analysis service definition.
    """
    def RequireAnalysis(self, request, context):
      """Sends an analysis request
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAnalysisStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The analysis service definition.
    """
    def RequireAnalysis(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends an analysis request
      """
      raise NotImplementedError()
    RequireAnalysis.future = None


  def beta_create_Analysis_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('analysis.Analysis', 'RequireAnalysis'): AnalysisRequest.FromString,
    }
    response_serializers = {
      ('analysis.Analysis', 'RequireAnalysis'): AnalysisReply.SerializeToString,
    }
    method_implementations = {
      ('analysis.Analysis', 'RequireAnalysis'): face_utilities.unary_unary_inline(servicer.RequireAnalysis),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Analysis_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('analysis.Analysis', 'RequireAnalysis'): AnalysisRequest.SerializeToString,
    }
    response_deserializers = {
      ('analysis.Analysis', 'RequireAnalysis'): AnalysisReply.FromString,
    }
    cardinalities = {
      'RequireAnalysis': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'analysis.Analysis', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
